all_joints:
- - 0
- - 1
- - 2
- - 3
all_joints_names:
- eyes
- swimbladder
- midtail
- endtail
alpha_r: 0.02
batch_size: 2
clahe: true
claheratio: 0.1
cropratio: 0.4
dataset: training-datasets/iteration-0/UnaugmentedDataSet_multiFishTest1Jun10/multiFishTest1_jamie95shuffle1.pickle
dataset_type: multi-animal-imgaug
decay_steps: 30000
display_iters: 500
edge: false
emboss:
  alpha:
  - 0.0
  - 1.0
  embossratio: 0.1
  strength:
  - 0.5
  - 1.5
global_scale: 0.8
histeq: true
histeqratio: 0.1
init_weights: /home/jamie/anaconda3/envs/DLC-GPU/lib/python3.7/site-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
lr_init: 0.0005
max_input_size: 1500
metadataset: training-datasets/iteration-0/UnaugmentedDataSet_multiFishTest1Jun10/Documentation_data-multiFishTest1_95shuffle1.pickle
min_input_size: 64
mirror: false
multi_step:
- - 0.0001
  - 7500
- - 5.0e-05
  - 12000
- - 1.0e-05
  - 200000
net_type: resnet_50
num_joints: 4
num_limbs: 6
optimizer: adam
pafwidth: 20
pairwise_huber_loss: false
pairwise_loss_weight: 0.1
pairwise_predict: false
partaffinityfield_graph:
- - 0
  - 1
- - 1
  - 2
- - 2
  - 3
- - 0
  - 3
- - 0
  - 2
- - 1
  - 3
partaffinityfield_predict: true
pos_dist_thresh: 17
project_path: /home/jamie/projects/deeplabcut/multiFishTracking/multiFishTest1-jamie-2021-06-10
rotation: 25
rotratio: 0.4
save_iters: 10000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
sharpen: false
sharpenratio: 0.3
weigh_only_present_joints: false
